export const HABIT_SUGGESTIONS = ["Workout", "Gym", "Running", "Meditation", "Yoga", "Reading", "Journaling", "Drink Water", "Coding", "Study", "Walking", "Stretching", "Sleep Early", "Practice Music", "Learn Language", "Cold Shower", "Healthy Meal", "No Sugar", "Plan Day", "Wake Up Early",
    "Morning Walk",
    "Evening Walk",
    "Deep Breathing",
    "Gratitude Practice",
    "Affirmations",
    "Digital Detox",
    "No Social Media",
    "Limit Screen Time",
    "Clean Room",
    "Make Bed",
    "Daily Planning",
    "Review Goals",
    "Track Expenses",
    "Save Money",
    "Read News",
    "Read 10 Pages",
    "Write Blog",
    "Write Notes",
    "Practice Typing",
    "Practice Coding",
    "Solve Problems",
    "Learn Algorithm",
    "Build Project",
    "Open Source",
    "Learn Design",
    "Practice UI",
    "Sketch Ideas",
    "Creative Writing",
    "Brainstorm Ideas",
    "Mind Mapping",
    "Learn Vocabulary",
    "Practice Speaking",
    "Watch Lecture",
    "Online Course",
    "Skill Practice",
    "Practice Math",
    "Revise Notes",
    "Flashcards",
    "Practice Guitar",
    "Practice Piano",
    "Practice Singing",
    "Listen Podcast",
    "Listen Audiobook",
    "Nature Walk",
    "Sunlight Exposure",
    "Posture Check",
    "Eye Exercise",
    "Hydration Check",
    "Eat Fruits",
    "Eat Vegetables",
    "Protein Intake",
    "Healthy Snacks",
    "No Junk Food",
    "Cook Meal",
    "Meal Prep",
    "Drink Green Tea",
    "Take Vitamins",
    "Step Goal",
    "10k Steps",
    "Cardio",
    "Strength Training",
    "Push Ups",
    "Pull Ups",
    "Squats",
    "Plank",
    "Jump Rope",
    "Cycling",
    "Swimming",
    "Sports Practice",
    "Stretch Break",
    "Foam Rolling",
    "Mobility Work",
    "Breathwork",
    "Cold Exposure",
    "Ice Bath",
    "Sleep 8 Hours",
    "Night Routine",
    "Morning Routine",
    "Evening Reflection",
    "Daily Review",
    "Weekly Review",
    "Declutter",
    "Organize Desk",
    "Inbox Zero",
    "Backup Files",
    "Update Portfolio",
    "Network Online",
    "LinkedIn Post",
    "Read Research",
    "Learn AI",
    "Learn ML",
    "Learn System Design",
    "Learn DevOps",
    "Learn Security",
    "Practice Debugging",
    "Write Tests",
    "Code Review",
    "Documentation",
    "Refactor Code",
    "Learn Git",
    "Practice DSA",
    "Solve Leetcode",
    "Side Project",
    "Startup Ideas",
    "Market Research",
    "Customer Feedback",
    "Daily Reflection",
    "Self Reflection",
    "Gratitude Journal",
    "Mood Tracking",
    "Habit Tracking",
    "Minimalism",
    "Donate Items",
    "Help Someone",
    "Random Kindness",
    "Call Family",
    "Meet Friends",
    "Social Break",
    "Offline Time",
    "Prayer",
    "Spiritual Reading",
    "Meditation 10 Min",
    "Focus Session",
    "Pomodoro Session",
    "Deep Work",
    "No Procrastination",
    "Task Prioritization",
    "Goal Visualization"];